In [1]:
import pandas as pd

pd.read_parquet("monitor_reviews.parquet").tail(3)

,idx,review,productName
746,53623,높은 주사율로 인해 빠른 움직임도 문제없이 출력해주니 사용시 눈에 피로도가 많이 줄...,옵틱스 MSI G271 게이밍 144 아이세이버 무결점
747,53624,주문 후 24시간 안에 택배 받았습니다. 이상 없이 잘 작동되고 가성비도 괜찮고 조...,옵틱스 MSI G271 게이밍 144 아이세이버 무결점
748,53625,HDMI 케이블이 구성되어있지 않아서 아쉽습니다 ㅜ 무게도 가벼운편이라 이리저리 움...,옵틱스 MSI G271 게이밍 144 아이세이버 무결점

In [5]:
pd.read_parquet("monitor_opinion_units.parquet").tail(3)

,idx,review_idx,raw_aspect,raw_status,excerpt,opinion,sentiment
2580,2581,53625,HDMI 케이블 구성,미포함,HDMI 케이블이 구성되어있지 않아서 아쉽습니다 ㅜ,HDMI 케이블이 구성되어 있지 않아 아쉬움,negative
2581,2582,53625,무게,가벼움,무게도 가벼운편이라 이리저리 움직이고 안타깝네요,무게가 가벼운 편이라 아쉬움,negative
2582,2583,53625,거치 안정성,낮음,무게도 가벼운편이라 이리저리 움직이고 안타깝네요,무게가 가벼운 편이라 모니터가 이리저리 움직임,negative

In [ ]:
pd.read_parquet("monitor_representative_attributes.parquet").tail(3)

       idx  review_idx raw_attribute sentiment
2349  2350       53625   HDMI 케이블 구성  negative
2350  2351       53625            무게  negative
2351  2352       53625           안정성  negative